theme: jekyll-theme-minimal

name: Princeton Academy
title: Princeton Academy
description: Personalized educational consulting for exceptional students.

logo: /assets/images/test1.png
github:
  is_project_page: false
